"use strict";this.default_host=this.default_host||{};(function(_){var window=this;
try{
var aa,ba,ca,ea,da,ha,ia,ka,la;
for(_.g,aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ba="undefined"!=typeof window&&window===this?this:"undefined"!=typeof window.global&&null!=window.global?window.global:this,ca=function(){ca=function(){};ba.Symbol||(ba.Symbol=da)},ea=0,da=function(a){return"jscomp_symbol_"+(a||"")+ea++},_.ga=function(){ca();var a=ba.Symbol.iterator;
a||(a=ba.Symbol.iterator=ba.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return _.fa(this)}});_.ga=function(){}},_.fa=function(a){var b=0;return ha(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})},ha=function(a){_.ga();a={next:a};a[ba.Symbol.iterator]=function(){return this};return a},ia=ba,ka=["String","prototype","repeat"],la=0;la<ka.length-1;la++){var ma=ka[la];ma in ia||(ia[ma]={});ia=ia[ma]}
var na=ka[ka.length-1],oa=ia[na],pa=oa?oa:function(a){var b;if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");b=this+"";if(0>a||1342177279<a)throw new window.RangeError("Invalid count value");a|=0;for(var c="";a;)if(a&1&&(c+=b),a>>>=1)b+=b;return c};pa!=oa&&null!=pa&&aa(ia,na,{configurable:!0,writable:!0,value:pa});_.qa=_.qa||{};_.l=this;_.ra="closure_uid_"+(1E9*Math.random()>>>0);_.sa=Date.now||function(){return+new Date};

}catch(e){_._DumpException(e)}
try{
var ta,ua;_.m=function(a){return void 0!==a};ta=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};ua=function(a,b,c){return a.call.apply(a.bind,arguments)};
_.va=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.p=function(a,b){function c(){}c.prototype=b.prototype;a.A=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Dc=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};
_.wa=function(a,b){var c=a.split("."),d=_.l;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.m(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};_.xa=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.r=function(a,b,c){_.r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ua:ta;return _.r.apply(null,arguments)};
_.ya=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.za=function(a){return"function"==_.va(a)};_.Aa=function(a){return"number"==typeof a};_.t=function(a){return"string"==typeof a};_.Ba=function(a){var b=_.va(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.Ca=function(a){return"array"==_.va(a)};_.Da=function(){};_.Ea=function(a){a=a.split(".");for(var b=_.l,c;c=a.shift();)if(null!=b[c])b=b[c];else return null;return b};
_.Fa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.Fa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.p(_.Fa,Error);_.Fa.prototype.name="CustomError";var Ga;var Ka,Ma,Na,Oa,Pa,Qa,Ra,La,Ta,Wa;_.Ha=function(a,b){return 0==a.lastIndexOf(b,0)};_.Ia=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};_.Ja=function(a){return/^[\s\xa0]*$/.test(a)};Ka=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
_.Sa=function(a){if(!La.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Ma,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Na,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Oa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Pa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Qa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ra,"&#0;"));return a};Ma=/&/g;Na=/</g;Oa=/>/g;Pa=/"/g;Qa=/'/g;Ra=/\x00/g;La=/[\x00&<>"']/;Ta=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};
_.Ua=function(a){return null==a?"":String(a)};_.Va=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,_.sa)()).toString(36)};
_.Xa=function(a,b){for(var c=0,d=Ka(String(a)).split("."),e=Ka(String(b)).split("."),f=Math.max(d.length,e.length),h=0;0==c&&h<f;h++){var k=d[h]||"",n=e[h]||"";do{k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];n=/(\d*)(\D*)(.*)/.exec(n)||["","","",""];if(0==k[0].length&&0==n[0].length)break;c=Wa(0==k[1].length?0:(0,window.parseInt)(k[1],10),0==n[1].length?0:(0,window.parseInt)(n[1],10))||Wa(0==k[2].length,0==n[2].length)||Wa(k[2],n[2]);k=k[3];n=n[3]}while(0==c)}return c}; Wa=function(a,b){return a<b?-1:a>b?1:0};
var Ya;Ya=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.t(a))return _.t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.u=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.Za=function(a,b){for(var c=_.t(a)?a.split(""):a,d=a.length-1;0<=d;--d)d in c&&b.call(void 0,c[d],d,a)};_.$a=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=_.t(a)?a.split(""):a,k=0;k<d;k++)if(k in h){var n=h[k];b.call(c,n,k,a)&&(e[f++]=n)}return e};
_.ab=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.t(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};_.bb=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.db=function(a,b){var c=_.cb(a,b,void 0);return 0>c?null:_.t(a)?a.charAt(c):a[c]};
_.cb=function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};_.eb=function(a,b){return 0<=Ya(a,b)};_.gb=function(a,b){var c=Ya(a,b),d;(d=0<=c)&&_.fb(a,c);return d};_.fb=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};_.hb=function(a){return Array.prototype.concat.apply(Array.prototype,arguments)};_.ib=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
a:{var kb=_.l.navigator;if(kb){var lb=kb.userAgent;if(lb){_.jb=lb;break a}}_.jb=""}_.w=function(a){return-1!=_.jb.indexOf(a)};var nb,ob,pb,rb;_.mb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};nb=function(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};ob=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};pb=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};_.qb=function(a){var b={},c;for(c in a)b[c]=a[c];return b};rb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "); _.sb=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<rb.length;f++)c=rb[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
var tb=function(){return(_.w("Chrome")||_.w("CriOS"))&&!_.w("Edge")};var ub;ub=function(){return _.w("iPhone")&&!_.w("iPod")&&!_.w("iPad")};_.vb=function(){return _.w("Macintosh")};_.wb=function(){return _.w("Windows")};var xb=function(a){xb[" "](a);return a};xb[" "]=_.Da;_.yb=function(a,b){try{return xb(a[b]),!0}catch(c){}return!1};_.zb=function(a,b,c){return Object.prototype.hasOwnProperty.call(a,b)?a[b]:a[b]=c(b)};var Ab,Bb,Eb,Ib,Jb,Nb,Ob,Qb;Ab=_.w("Opera");_.x=_.w("Trident")||_.w("MSIE");Bb=_.w("Edge");_.Cb=_.w("Gecko")&&!(-1!=_.jb.toLowerCase().indexOf("webkit")&&!_.w("Edge"))&&!(_.w("Trident")||_.w("MSIE"))&&!_.w("Edge");_.Db=-1!=_.jb.toLowerCase().indexOf("webkit")&&!_.w("Edge");Eb=_.l.navigator||null;_.Fb=Eb&&Eb.platform||"";_.Gb=_.vb();_.Hb=_.wb();Ib=function(){var a=_.l.document;return a?a.documentMode:void 0};
a:{var Kb="",Lb=function(){var a=_.jb;if(_.Cb)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Bb)return/Edge\/([\d\.]+)/.exec(a);if(_.x)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.Db)return/WebKit\/(\S+)/.exec(a);if(Ab)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Lb&&(Kb=Lb?Lb[1]:"");if(_.x){var Mb=Ib();if(null!=Mb&&Mb>(0,window.parseFloat)(Kb)){Jb=String(Mb);break a}}Jb=Kb}Nb=Jb;Ob={};_.Pb=function(a){return _.zb(Ob,a,function(){return 0<=_.Xa(Nb,a)})};var Rb=_.l.document; Qb=Rb&&_.x?Ib()||("CSS1Compat"==Rb.compatMode?(0,window.parseInt)(Nb,10):5):void 0;
var Sb=_.w("Firefox"),Tb=ub()||_.w("iPod"),Ub=_.w("iPad"),Vb=_.w("Android")&&!(tb()||_.w("Firefox")||_.w("Opera")||_.w("Silk")),Wb=tb(),Xb=_.w("Safari")&&!(tb()||_.w("Coast")||_.w("Opera")||_.w("Edge")||_.w("Silk")||_.w("Android"))&&!(ub()||_.w("iPad")||_.w("iPod"));
var Yb=null;var Zb,$b,bc,ac,ec,fc,dc;Zb=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))};$b=function(a){a=String(a);if(Zb(a))try{return eval("("+a+")")}catch(b){}throw Error("c`"+a);};_.cc=function(a,b){var c=[];ac(new bc(b),a,c);return c.join("")};
bc=function(a){this.a=a};
ac=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(_.Ca(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),e=d[f],ac(a,a.a?a.a.call(d,String(f),e):e,c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");f="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(e=b[d],"function"!=typeof e&&(c.push(f),dc(d,c),c.push(":"),ac(a,a.a?a.a.call(b,d,e):e,c),f=","));c.push("}");return}}switch(typeof b){case "string":dc(b,
c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("d`"+typeof b);}}};ec={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"};fc=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g; dc=function(a,b){b.push('"',a.replace(fc,function(a){var b=ec[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),ec[a]=b);return b}),'"')};
var ic,kc,lc,oc;_.y=function(){};_.gc="function"==typeof window.Uint8Array;_.z=function(a,b,c,d,e){a.b=null;b||(b=c?[c]:[]);a.D=c?String(c):void 0;a.h=0===c?-1:0;a.g=b;a:{if(a.g.length&&(b=a.g.length-1,(c=a.g[b])&&"object"==typeof c&&!_.Ca(c)&&!(_.gc&&c instanceof window.Uint8Array))){a.C=b-a.h;a.c=c;break a}a.C=Number.MAX_VALUE}a.v={};if(d)for(b=0;b<d.length;b++)c=d[b],c<a.C?(c+=a.h,a.g[c]=a.g[c]||_.hc):a.c[c]=a.c[c]||_.hc;e&&e.length&&(0,_.u)(e,_.xa(ic,a))};_.hc=[];
_.A=function(a,b){if(b<a.C){var c=b+a.h,d=a.g[c];return d===_.hc?a.g[c]=[]:d}d=a.c[b];return d===_.hc?a.c[b]=[]:d};_.jc=function(a,b,c){a=_.A(a,b);return null==a?c:a};_.B=function(a,b,c){b<a.C?a.g[b+a.h]=c:a.c[b]=c};ic=function(a,b){var c,d;(0,_.u)(b,function(b){var e=_.A(a,b);null!=e&&(c=b,d=e,_.B(a,b,void 0))});return c?(_.B(a,c,d),c):0};_.C=function(a,b,c){a.b||(a.b={});if(!a.b[c]){var d=_.A(a,c);d&&(a.b[c]=new b(d))}return a.b[c]};
_.E=function(a,b,c){a.b||(a.b={});var d=c?_.D(c):c;a.b[b]=c;_.B(a,b,d)};kc=function(a){if(a.b)for(var b in a.b){var c=a.b[b];if(_.Ca(c))for(var d=0;d<c.length;d++)c[d]&&_.D(c[d]);else c&&_.D(c)}};_.D=function(a){kc(a);return a.g};lc=_.l.JSON&&_.l.JSON.stringify||"object"===typeof JSON&&JSON.stringify;
_.y.prototype.j=_.gc?function(){var a=window.Uint8Array.prototype.toJSON;window.Uint8Array.prototype.toJSON=function(){if(!Yb){Yb={};for(var a=0;65>a;a++)Yb[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)}for(var a=Yb,b=[],e=0;e<this.length;e+=3){var f=this[e],h=e+1<this.length,k=h?this[e+1]:0,n=e+2<this.length,q=n?this[e+2]:0,v=f>>2,f=(f&3)<<4|k>>4,k=(k&15)<<2|q>>6,q=q&63;n||(q=64,h||(k=64));b.push(a[v],a[f],a[k],a[q])}return b.join("")};try{var b=lc.call(null,_.D(this),
mc)}finally{window.Uint8Array.prototype.toJSON=a}return b}:lc?function(){return lc.call(null,_.D(this),mc)}:function(){return _.cc(_.D(this),mc)};var mc=function(a,b){if(_.Aa(b)){if((0,window.isNaN)(b))return"NaN";if(window.Infinity===b)return"Infinity";if(-window.Infinity===b)return"-Infinity"}return b};_.y.prototype.toString=function(){kc(this);return this.g.toString()};oc=function(a,b){a=a||{};b=b||{};var c={},d;for(d in a)c[d]=0;for(d in b)c[d]=0;for(d in c)if(!_.nc(a[d],b[d]))return!1;return!0};
_.nc=function(a,b){if(a==b)return!0;if(!_.ya(a)||!_.ya(b)||a.constructor!=b.constructor)return!1;if(_.gc&&a.constructor===window.Uint8Array){if(a.length!=b.length)return!1;for(var c=0;c<a.length;c++)if(a[c]!=b[c])return!1;return!0}if(a.constructor===Array){for(var d=void 0,e=void 0,f=Math.max(a.length,b.length),c=0;c<f;c++){var h=a[c],k=b[c];h&&h.constructor==Object&&(d=h,h=void 0);k&&k.constructor==Object&&(e=k,k=void 0);if(!_.nc(h,k))return!1}return d||e?(d=d||{},e=e||{},oc(d,e)):!0}if(a.constructor=== Object)return oc(a,b);throw Error("e");};
_.F=function(){this.I=this.I;this.C=this.C};_.F.prototype.I=!1;_.F.prototype.$=function(){this.I||(this.I=!0,this.w())};_.I=function(a,b){_.G(a,_.xa(_.H,b))};_.G=function(a,b,c){a.I?_.m(c)?b.call(c):b():(a.C||(a.C=[]),a.C.push(_.m(c)?(0,_.r)(b,c):b))};_.F.prototype.w=function(){if(this.C)for(;this.C.length;)this.C.shift()()};_.H=function(a){a&&"function"==typeof a.$&&a.$()};
var pc=!_.x||9<=Number(Qb);!_.Cb&&!_.x||_.x&&9<=Number(Qb)||_.Cb&&_.Pb("1.9.1");_.x&&_.Pb("9");_.qc=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;_.sc=function(){this.a="";this.g=_.rc;this.b=null};_.sc.prototype.ab=!0;_.sc.prototype.La=function(){return this.b};_.sc.prototype.bb=!0;_.sc.prototype.$a=function(){return this.a};_.rc={};_.tc=function(a,b){var c=new _.sc;c.a=a;c.b=b;return c};_.tc("<!DOCTYPE html>",0);_.tc("",0);_.uc=_.tc("<br>",0);
var Ac,Dc,Cc;_.xc=function(a){return a?new _.vc(_.wc(a)):Ga||(Ga=new _.vc)};_.zc=function(a,b){var c=b||window.document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=_.yc(window.document,"*",a,b)[0];return d||null};
_.yc=function(a,b,c,d){a=d||a;b=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,h;h=a[f];f++)b==h.nodeName&&(d[e++]=h);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;h=a[f];f++)b=h.className,"function"==typeof b.split&&_.eb(b.split(/\s+/),c)&&(d[e++]=h);d.length=e;return d}return a};
_.Bc=function(a,b){_.mb(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Ac.hasOwnProperty(d)?a.setAttribute(Ac[d],b):_.Ha(d,"aria-")||_.Ha(d,"data-")?a.setAttribute(d,b):a[d]=b})};Ac={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
Dc=function(a,b,c){function d(c){c&&b.appendChild(_.t(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];!_.Ba(f)||_.ya(f)&&0<f.nodeType?d(f):(0,_.u)(Cc(f)?_.ib(f):f,d)}};_.Ec=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.wc=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};Cc=function(a){if(a&&"number"==typeof a.length){if(_.ya(a))return"function"==typeof a.item||"string"==typeof a.item;if(_.za(a))return"function"==typeof a.item}return!1};
_.vc=function(a){this.a=a||_.l.document||window.document};_.g=_.vc.prototype;_.g.za=_.xc;_.g.B=function(a){return _.t(a)?this.a.getElementById(a):a};
_.g.ma=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),h=e[1];if(!pc&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',_.Sa(h.name),'"');if(h.type){f.push(' type="',_.Sa(h.type),'"');var k={};_.sb(k,h);delete k.type;h=k}f.push(">");f=f.join("")}f=d.createElement(f);h&&(_.t(h)?f.className=h:_.Ca(h)?f.className=h.join(" "):_.Bc(f,h));2<e.length&&Dc(d,f,e);return f};_.g.appendChild=function(a,b){a.appendChild(b)}; _.g.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};
_.Fc=function(a){return function(){return a}}(!1);var Gc="StopIteration"in _.l?_.l.StopIteration:{message:"StopIteration",stack:""},Hc=function(){};Hc.prototype.next=function(){throw Gc;};Hc.prototype.ha=function(){return this};
var Ic=function(a){if(a instanceof Hc)return a;if("function"==typeof a.ha)return a.ha(!1);if(_.Ba(a)){var b=0,c=new Hc;c.next=function(){for(;;){if(b>=a.length)throw Gc;if(b in a)return a[b++];b++}};return c}throw Error("f");},Jc=function(a,b){if(_.Ba(a))try{(0,_.u)(a,b,void 0)}catch(c){if(c!==Gc)throw c;}else{a=Ic(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(c){if(c!==Gc)throw c;}}},Kc=function(a){if(_.Ba(a))return _.ib(a);a=Ic(a);var b=[];Jc(a,function(a){b.push(a)});return b};
_.J=function(a,b){this.b={};this.a=[];this.c=this.g=0;var c=arguments.length;if(1<c){if(c%2)throw Error("b");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof _.J?(c=a.V(),d=a.S()):(c=pb(a),d=ob(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.J.prototype.S=function(){Lc(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.J.prototype.V=function(){Lc(this);return this.a.concat()};_.Nc=function(a,b){return Mc(a.b,b)};
_.J.prototype.clear=function(){this.b={};this.c=this.g=this.a.length=0};_.J.prototype.remove=function(a){return Mc(this.b,a)?(delete this.b[a],this.g--,this.c++,this.a.length>2*this.g&&Lc(this),!0):!1};var Lc=function(a){if(a.g!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];Mc(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.g!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],Mc(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.J.prototype.get=function(a,b){return Mc(this.b,a)?this.b[a]:b};
_.J.prototype.set=function(a,b){Mc(this.b,a)||(this.g++,this.a.push(a),this.c++);this.b[a]=b};_.J.prototype.forEach=function(a,b){for(var c=this.V(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};_.J.prototype.ha=function(a){Lc(this);var b=0,c=this.c,d=this,e=new Hc;e.next=function(){if(c!=d.c)throw Error("g");if(b>=d.a.length)throw Gc;var e=d.a[b++];return a?e:d.b[e]};return e};var Mc=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var Pc;_.Oc=function(a){if(a.S&&"function"==typeof a.S)return a.S();if(_.t(a))return a.split("");if(_.Ba(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return ob(a)};
Pc=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);else if(_.Ba(a)||_.t(a))(0,_.u)(a,b,void 0);else{var c;if(a.V&&"function"==typeof a.V)c=a.V();else if(a.S&&"function"==typeof a.S)c=void 0;else if(_.Ba(a)||_.t(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=pb(a);for(var d=_.Oc(a),e=d.length,f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}};
var Qc=function(a,b,c){this.c=c;this.g=a;this.h=b;this.b=0;this.a=null};Qc.prototype.get=function(){var a;0<this.b?(this.b--,a=this.a,this.a=a.next,a.next=null):a=this.g();return a};var Rc=function(a,b){a.h(b);a.b<a.c&&(a.b++,b.next=a.a,a.a=b)};var Vc;_.Sc=[];_.Tc=[];_.Uc=!1;Vc=function(a){_.Sc[_.Sc.length]=a;if(_.Uc)for(var b=0;b<_.Tc.length;b++)a((0,_.r)(_.Tc[b].b,_.Tc[b]))};var Wc,Yc,Zc,Xc;Wc=function(a){_.l.setTimeout(function(){throw a;},0)};_.$c=function(a,b){var c=a;b&&(c=(0,_.r)(a,b));c=Xc(c);!_.za(_.l.setImmediate)||_.l.Window&&_.l.Window.prototype&&!_.w("Edge")&&_.l.Window.prototype.setImmediate==_.l.setImmediate?(Yc||(Yc=Zc()),Yc(c)):_.l.setImmediate(c)};
Zc=function(){var a=_.l.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.w("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,_.r)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!_.w("Trident")&&!_.w("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.m(c.next)){c=c.next;var a=c.lb;c.lb=null;a()}};return function(a){d.next={lb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=
window.document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.l.setTimeout(a,0)}};Xc=function(a){return a};Vc(function(a){Xc=a});
var ad=function(){this.b=this.a=null},cd=new Qc(function(){return new bd},function(a){a.reset()},100);ad.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var bd=function(){this.next=this.b=this.a=null};bd.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};bd.prototype.reset=function(){this.next=this.b=this.a=null};
var dd,ed,fd,gd,id;_.hd=function(a,b){dd||ed();fd||(dd(),fd=!0);var c=gd,d=cd.get();d.set(a,b);c.b?c.b.next=d:c.a=d;c.b=d};ed=function(){var a=_.l.Promise;if(-1!=String(a).indexOf("[native code]")){var b=a.resolve(void 0);dd=function(){b.then(id)}}else dd=function(){_.$c(id)}};fd=!1;gd=new ad;id=function(){for(var a;a=gd.remove();){try{a.a.call(a.b)}catch(b){Wc(b)}Rc(cd,a)}fd=!1};
var jd=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},kd=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var nd,od,pd,vd,zd,ld,Cd,yd,wd;_.md=function(a,b){this.a=0;this.C=void 0;this.c=this.b=this.g=null;this.h=this.j=!1;if(a!=_.Da)try{var c=this;a.call(b,function(a){ld(c,2,a)},function(a){ld(c,3,a)})}catch(d){ld(this,3,d)}};nd=function(){this.next=this.context=this.b=this.c=this.a=null;this.g=!1};nd.prototype.reset=function(){this.context=this.b=this.c=this.a=null;this.g=!1};od=new Qc(function(){return new nd},function(a){a.reset()},100);pd=function(a,b,c){var d=od.get();d.c=a;d.b=b;d.context=c;return d};
_.qd=function(a){if(a instanceof _.md)return a;var b=new _.md(_.Da);ld(b,2,a);return b};_.sd=function(){var a,b=new _.md(function(b){a=b});return new rd(b,a)};_.md.prototype.then=function(a,b,c){return _.td(this,_.za(a)?a:null,_.za(b)?b:null,c)};jd(_.md);_.md.prototype.cancel=function(a){0==this.a&&_.hd(function(){var b=new ud(a);vd(this,b)},this)};
vd=function(a,b){if(0==a.a)if(a.g){var c=a.g;if(c.b){for(var d=0,e=null,f=null,h=c.b;h&&(h.g||(d++,h.a==a&&(e=h),!(e&&1<d)));h=h.next)e||(f=h);e&&(0==c.a&&1==d?vd(c,b):(f?(d=f,d.next==c.c&&(c.c=d),d.next=d.next.next):wd(c),xd(c,e,3,b)))}a.g=null}else ld(a,3,b)};zd=function(a,b){a.b||2!=a.a&&3!=a.a||yd(a);a.c?a.c.next=b:a.b=b;a.c=b};
_.td=function(a,b,c,d){var e=pd(null,null,null);e.a=new _.md(function(a,h){e.c=b?function(c){try{var e=b.call(d,c);a(e)}catch(q){h(q)}}:a;e.b=c?function(b){try{var e=c.call(d,b);!_.m(e)&&b instanceof ud?h(b):a(e)}catch(q){h(q)}}:h});e.a.g=a;zd(a,e);return e.a};_.md.prototype.m=function(a){this.a=0;ld(this,2,a)};_.md.prototype.o=function(a){this.a=0;ld(this,3,a)};
ld=function(a,b,c){0==a.a&&(a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself")),a.a=1,_.Ad(c,a.m,a.o,a)||(a.C=c,a.a=b,a.g=null,yd(a),3!=b||c instanceof ud||Bd(a,c)))};_.Ad=function(a,b,c,d){if(a instanceof _.md)return zd(a,pd(b||_.Da,c||null,d)),!0;if(kd(a))return a.then(b,c,d),!0;if(_.ya(a))try{var e=a.then;if(_.za(e))return Cd(a,e,b,c,d),!0}catch(f){return c.call(d,f),!0}return!1};
Cd=function(a,b,c,d,e){var f=!1,h=function(a){f||(f=!0,c.call(e,a))},k=function(a){f||(f=!0,d.call(e,a))};try{b.call(a,h,k)}catch(n){k(n)}};yd=function(a){a.j||(a.j=!0,_.hd(a.l,a))};wd=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.c=null);return b};_.md.prototype.l=function(){for(var a;a=wd(this);)xd(this,a,this.a,this.C);this.j=!1};
var xd=function(a,b,c,d){if(3==c&&b.b&&!b.g)for(;a&&a.h;a=a.g)a.h=!1;if(b.a)b.a.g=null,Dd(b,c,d);else try{b.g?b.c.call(b.context):Dd(b,c,d)}catch(e){Ed.call(null,e)}Rc(od,b)},Dd=function(a,b,c){2==b?a.c.call(a.context,c):a.b&&a.b.call(a.context,c)},Bd=function(a,b){a.h=!0;_.hd(function(){a.h&&Ed.call(null,b)})},Ed=Wc,ud=function(a){_.Fa.call(this,a)};_.p(ud,_.Fa);ud.prototype.name="cancel";var rd=function(a,b){this.a=a;this.b=b};
/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
_.Fd=function(a,b){this.l=[];this.H=a;this.v=b||null;this.j=this.g=!1;this.c=void 0;this.J=this.K=this.o=!1;this.m=0;this.a=null;this.C=0};_.Fd.prototype.cancel=function(a){if(this.g)this.c instanceof _.Fd&&this.c.cancel();else{if(this.a){var b=this.a;delete this.a;a?b.cancel(a):(b.C--,0>=b.C&&b.cancel())}this.H?this.H.call(this.v,this):this.J=!0;this.g||this.D(new _.Gd)}};_.Fd.prototype.G=function(a,b){this.o=!1;Hd(this,a,b)};
var Hd=function(a,b,c){a.g=!0;a.c=c;a.j=!b;Id(a)},Kd=function(a){if(a.g){if(!a.J)throw new Jd;a.J=!1}};_.Fd.prototype.b=function(a){Kd(this);Hd(this,!0,a)};_.Fd.prototype.D=function(a){Kd(this);Hd(this,!1,a)};_.Md=function(a,b,c){_.Ld(a,b,null,c)};_.Ld=function(a,b,c,d){a.l.push([b,c,d]);a.g&&Id(a)};_.Fd.prototype.then=function(a,b,c){var d,e,f=new _.md(function(a,b){d=a;e=b});_.Ld(this,d,function(a){a instanceof _.Gd?f.cancel():e(a)});return f.then(a,b,c)};jd(_.Fd);
_.Nd=function(a,b){b instanceof _.Fd?_.Md(a,(0,_.r)(b.h,b)):_.Md(a,function(){return b})};_.Fd.prototype.h=function(a){var b=new _.Fd;_.Ld(this,b.b,b.D,b);a&&(b.a=this,this.C++);return b};
var Od=function(a){return(0,_.bb)(a.l,function(a){return _.za(a[1])})},Id=function(a){if(a.m&&a.g&&Od(a)){var b=a.m,c=Pd[b];c&&(_.l.clearTimeout(c.a),delete Pd[b]);a.m=0}a.a&&(a.a.C--,delete a.a);for(var b=a.c,d=c=!1;a.l.length&&!a.o;){var e=a.l.shift(),f=e[0],h=e[1],e=e[2];if(f=a.j?h:f)try{var k=f.call(e||a.v,b);_.m(k)&&(a.j=a.j&&(k==b||k instanceof Error),a.c=b=k);if(kd(b)||"function"===typeof _.l.Promise&&b instanceof _.l.Promise)d=!0,a.o=!0}catch(n){b=n,a.j=!0,Od(a)||(c=!0)}}a.c=b;d&&(k=(0,_.r)(a.G,
a,!0),d=(0,_.r)(a.G,a,!1),b instanceof _.Fd?(_.Ld(b,k,d),b.K=!0):b.then(k,d));c&&(b=new Qd(b),Pd[b.a]=b,a.m=b.a)},Jd=function(){_.Fa.call(this)};_.p(Jd,_.Fa);Jd.prototype.message="Deferred has already fired";Jd.prototype.name="AlreadyCalledError";_.Gd=function(){_.Fa.call(this)};_.p(_.Gd,_.Fa);_.Gd.prototype.message="Deferred was canceled";_.Gd.prototype.name="CanceledError";var Qd=function(a){this.a=_.l.setTimeout((0,_.r)(this.g,this),0);this.b=a}; Qd.prototype.g=function(){delete Pd[this.a];throw this.b;};var Pd={};
var Rd=!_.x||9<=Number(Qb),Sd=_.x&&!_.Pb("9");!_.Db||_.Pb("528");_.Cb&&_.Pb("1.9b")||_.x&&_.Pb("8")||Ab&&_.Pb("9.5")||_.Db&&_.Pb("528");_.Cb&&!_.Pb("8")||_.x&&_.Pb("9");_.K=function(a,b){this.type="undefined"!=typeof _.Td&&a instanceof _.Td?String(a):a;this.b=this.target=b;this.c=!1;this.qb=!0};_.K.prototype.l=function(){this.c=!0};_.K.prototype.g=function(){this.qb=!1};var Ud=function(a,b){_.K.call(this,a?a.type:"");this.b=this.target=null;this.keyCode=0;this.C=this.m=this.h=this.j=!1;this.a=this.state=null;if(a){this.type=a.type;this.target=a.target||a.srcElement;this.b=b;var c=a.relatedTarget;c&&_.Cb&&_.yb(c,"nodeName");this.keyCode=a.keyCode||0;this.j=a.ctrlKey;this.h=a.altKey;this.m=a.shiftKey;this.C=a.metaKey;this.state=a.state;this.a=a;a.defaultPrevented&&this.g()}};_.p(Ud,_.K);
Ud.prototype.l=function(){Ud.A.l.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};Ud.prototype.g=function(){Ud.A.g.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Sd)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var Vd="closure_listenable_"+(1E6*Math.random()|0),Wd=function(a){return!(!a||!a[Vd])},Xd=0;var Yd=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.xa=!!d;this.Na=e;this.key=++Xd;this.removed=this.Ja=!1},Zd=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.Na=null};var $d=function(a){this.src=a;this.a={};this.b=0},be=function(a,b,c,d,e,f){var h=b.toString();b=a.a[h];b||(b=a.a[h]=[],a.b++);var k=ae(b,c,e,f);-1<k?(a=b[k],d||(a.Ja=!1)):(a=new Yd(c,a.src,h,!!e,f),a.Ja=d,b.push(a));return a};$d.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=ae(e,b,c,d);return-1<b?(Zd(e[b]),_.fb(e,b),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var ce=function(a,b){var c=b.type;c in a.a&&_.gb(a.a[c],b)&&(Zd(b),0==a.a[c].length&&(delete a.a[c],a.b--))};$d.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,Zd(d[e]);delete this.a[c];this.b--}return b};
var de=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=ae(a,c,d,e));return-1<b?a[b]:null},ee=function(a){var b=_.m(void 0)?"undefined":void 0,c=_.m(b),d=c?b.toString():"",e=_.m(void 0);return nb(a.a,function(a){for(var b=0;b<a.length;++b)if(!(c&&a[b].type!=d||e&&void 0!=a[b].xa))return!0;return!1})},ae=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.xa==!!c&&f.Na==d)return e}return-1};
var fe,ge,he,ke,me,re,ne,te,se,oe,le,ue,je;fe="closure_lm_"+(1E6*Math.random()|0);ge={};he=0;_.ie=function(a,b,c,d,e){if(_.Ca(b)){for(var f=0;f<b.length;f++)_.ie(a,b[f],c,d,e);return null}c=je(c);return Wd(a)?a.listen(b,c,d,e):ke(a,b,c,!1,d,e)};
ke=function(a,b,c,d,e,f){if(!b)throw Error("h");var h=!!e,k=le(a);k||(a[fe]=k=new $d(a));c=be(k,b,c,d,e,f);if(c.proxy)return c;d=me();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,h);else if(a.attachEvent)a.attachEvent(ne(b.toString()),d);else throw Error("i");he++;return c};me=function(){var a=oe,b=Rd?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};
_.pe=function(a,b,c,d,e){if(_.Ca(b)){for(var f=0;f<b.length;f++)_.pe(a,b[f],c,d,e);return null}c=je(c);return Wd(a)?a.Ma(b,c,d,e):ke(a,b,c,!0,d,e)};_.qe=function(a,b,c,d,e){if(_.Ca(b))for(var f=0;f<b.length;f++)_.qe(a,b[f],c,d,e);else c=je(c),Wd(a)?a.Qa(b,c,d,e):a&&(a=le(a))&&(b=de(a,b,c,!!d,e))&&re(b)};
re=function(a){if(!_.Aa(a)&&a&&!a.removed){var b=a.src;if(Wd(b))ce(b.g,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.xa):b.detachEvent&&b.detachEvent(ne(c),d);he--;(c=le(b))?(ce(c,a),0==c.b&&(c.src=null,b[fe]=null)):Zd(a)}}};ne=function(a){return a in ge?ge[a]:ge[a]="on"+a};te=function(a,b,c,d){var e=!0;if(a=le(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.xa==c&&!f.removed&&(f=se(f,d),e=e&&!1!==f)}return e};
se=function(a,b){var c=a.listener,d=a.Na||a.src;a.Ja&&re(a);return c.call(d,b)};
oe=function(a,b){if(a.removed)return!0;if(!Rd){var c=b||_.Ea("window.event"),d=new Ud(c,this),e=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var f=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(n){f=!0}if(f||void 0==c.returnValue)c.returnValue=!0}c=[];for(f=d.b;f;f=f.parentNode)c.push(f);for(var f=a.type,h=c.length-1;!d.c&&0<=h;h--){d.b=c[h];var k=te(c[h],f,!0,d),e=e&&k}for(h=0;!d.c&&h<c.length;h++)d.b=c[h],k=te(c[h],f,!1,d),e=e&&k}return e}return se(a,new Ud(b,this))}; le=function(a){a=a[fe];return a instanceof $d?a:null};ue="__closure_events_fn_"+(1E9*Math.random()>>>0);je=function(a){if(_.za(a))return a;a[ue]||(a[ue]=function(b){return a.handleEvent(b)});return a[ue]};Vc(function(a){oe=a(oe)});
_.L=function(){_.F.call(this);this.g=new $d(this);this.fa=this;this.J=null};_.p(_.L,_.F);_.L.prototype[Vd]=!0;_.L.prototype.G=function(a){this.J=a};_.L.prototype.removeEventListener=function(a,b,c,d){_.qe(this,a,b,c,d)};
_.M=function(a,b){var c,d=a.J;if(d)for(c=[];d;d=d.J)c.push(d);var d=a.fa,e=b,f=e.type||e;if(_.t(e))e=new _.K(e,d);else if(e instanceof _.K)e.target=e.target||d;else{var h=e,e=new _.K(f,d);_.sb(e,h)}var h=!0,k;if(c)for(var n=c.length-1;!e.c&&0<=n;n--)k=e.b=c[n],h=k.oa(f,!0,e)&&h;e.c||(k=e.b=d,h=k.oa(f,!0,e)&&h,e.c||(h=k.oa(f,!1,e)&&h));if(c)for(n=0;!e.c&&n<c.length;n++)k=e.b=c[n],h=k.oa(f,!1,e)&&h;return h};_.g=_.L.prototype;
_.g.w=function(){_.L.A.w.call(this);this.g&&this.g.removeAll(void 0);this.J=null};_.g.listen=function(a,b,c,d){return be(this.g,String(a),b,!1,c,d)};_.g.Ma=function(a,b,c,d){return be(this.g,String(a),b,!0,c,d)};_.g.Qa=function(a,b,c,d){return this.g.remove(String(a),b,c,d)}; _.g.oa=function(a,b,c){a=this.g.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.xa==b){var h=f.listener,k=f.Na||f.src;f.Ja&&ce(this.g,f);d=!1!==h.call(k,c)&&d}}return d&&0!=c.qb};
var ve=function(){};ve.prototype.a=null;var xe=function(a){var b;(b=a.a)||(b={},we(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var ye,ze=function(){};_.p(ze,ve);var Ae=function(a){return(a=we(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},we=function(a){if(!a.b&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.b=d}catch(e){}}throw Error("j");}return a.b};ye=new ze;
_.Be=function(a,b){_.L.call(this);this.b=a||1;this.a=b||_.l;this.c=(0,_.r)(this.rc,this);this.h=(0,_.sa)()};_.p(_.Be,_.L);_.g=_.Be.prototype;_.g.ra=!1;_.g.W=null;_.g.setInterval=function(a){this.b=a;this.W&&this.ra?(this.stop(),this.start()):this.W&&this.stop()};
_.g.rc=function(){if(this.ra){var a=(0,_.sa)()-this.h;0<a&&a<.8*this.b?this.W=this.a.setTimeout(this.c,this.b-a):(this.W&&(this.a.clearTimeout(this.W),this.W=null),_.M(this,"tick"),this.ra&&(this.W=this.a.setTimeout(this.c,this.b),this.h=(0,_.sa)()))}};_.g.start=function(){this.ra=!0;this.W||(this.W=this.a.setTimeout(this.c,this.b),this.h=(0,_.sa)())};_.g.stop=function(){this.ra=!1;this.W&&(this.a.clearTimeout(this.W),this.W=null)};_.g.w=function(){_.Be.A.w.call(this);this.stop();delete this.a}; _.Ce=function(a,b,c){if(_.za(a))c&&(a=(0,_.r)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.r)(a.handleEvent,a);else throw Error("k");return 2147483647<Number(b)?-1:_.l.setTimeout(a,b||0)};_.De=function(a){_.l.clearTimeout(a)};
var Ee=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,Fe=function(a,b){if(a)for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),f,h=null;0<=e?(f=c[d].substring(0,e),h=c[d].substring(e+1)):f=c[d];b(f,h?(0,window.decodeURIComponent)(h.replace(/\+/g," ")):"")}};
var Ge=function(a){_.L.call(this);this.headers=new _.J;this.D=a||null;this.b=!1;this.v=this.a=null;this.M="";this.j=0;this.h="";this.c=this.K=this.m=this.H=!1;this.l=0;this.o=null;this.Z="";this.T=this.U=!1},He,Ie,Re,Qe,Ne,Se,Te;_.p(Ge,_.L);He=/^https?$/i;Ie=["POST","PUT"];_.Je=[];_.Ke=function(a,b,c,d,e,f,h){var k=new Ge;_.Je.push(k);b&&k.listen("complete",b);k.Ma("ready",k.ga);f&&(k.l=Math.max(0,f));h&&(k.U=h);k.send(a,c,d,e)};Ge.prototype.ga=function(){this.$();_.gb(_.Je,this)};
Ge.prototype.send=function(a,b,c,d){if(this.a)throw Error("l`"+this.M+"`"+a);b=b?b.toUpperCase():"GET";this.M=a;this.h="";this.j=0;this.H=!1;this.b=!0;this.a=this.D?Ae(this.D):Ae(ye);this.v=this.D?xe(this.D):xe(ye);this.a.onreadystatechange=(0,_.r)(this.Y,this);try{this.K=!0,this.a.open(b,String(a),!0),this.K=!1}catch(f){Le(this,f);return}a=c||"";var e=new _.J(this.headers);d&&Pc(d,function(a,b){e.set(b,a)});d=_.db(e.V(),Me);c=_.l.FormData&&a instanceof _.l.FormData;!_.eb(Ie,b)||d||c||e.set("Content-Type",
"application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.Z&&(this.a.responseType=this.Z);"withCredentials"in this.a&&this.a.withCredentials!==this.U&&(this.a.withCredentials=this.U);try{Ne(this),0<this.l&&((this.T=Oe(this.a))?(this.a.timeout=this.l,this.a.ontimeout=(0,_.r)(this.X,this)):this.o=_.Ce(this.X,this.l,this)),this.m=!0,this.a.send(a),this.m=!1}catch(f){Le(this,f)}};
var Oe=function(a){return _.x&&_.Pb(9)&&_.Aa(a.timeout)&&_.m(a.ontimeout)},Me=function(a){return"content-type"==a.toLowerCase()};Ge.prototype.X=function(){"undefined"!=typeof _.qa&&this.a&&(this.h="Timed out after "+this.l+"ms, aborting",this.j=8,_.M(this,"timeout"),this.abort(8))};var Le=function(a,b){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);a.h=b;a.j=5;Pe(a);Qe(a)},Pe=function(a){a.H||(a.H=!0,_.M(a,"complete"),_.M(a,"error"))};
Ge.prototype.abort=function(a){this.a&&this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1,this.j=a||7,_.M(this,"complete"),_.M(this,"abort"),Qe(this))};Ge.prototype.w=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),Qe(this,!0));Ge.A.w.call(this)};Ge.prototype.Y=function(){this.I||(this.K||this.m||this.c?Re(this):this.N())};Ge.prototype.N=function(){Re(this)};
Re=function(a){if(a.b&&"undefined"!=typeof _.qa&&(!a.v[1]||4!=Se(a)||2!=Te(a)))if(a.m&&4==Se(a))_.Ce(a.Y,0,a);else if(_.M(a,"readystatechange"),4==Se(a)){a.b=!1;try{if(_.Ue(a))_.M(a,"complete"),_.M(a,"success");else{a.j=6;var b;try{b=2<Se(a)?a.a.statusText:""}catch(c){b=""}a.h=b+" ["+Te(a)+"]";Pe(a)}}finally{Qe(a)}}};Qe=function(a,b){if(a.a){Ne(a);var c=a.a,d=a.v[0]?_.Da:null;a.a=null;a.v=null;b||_.M(a,"ready");try{c.onreadystatechange=d}catch(e){}}};
Ne=function(a){a.a&&a.T&&(a.a.ontimeout=null);_.Aa(a.o)&&(_.De(a.o),a.o=null)};_.Ue=function(a){var b=Te(a),c;a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=String(a.M).match(Ee)[1]||null,!a&&_.l.self&&_.l.self.location&&(a=_.l.self.location.protocol,a=a.substr(0,a.length-1)),b=!He.test(a?a.toLowerCase():"");c=b}return c};Se=function(a){return a.a?a.a.readyState:0};Te=function(a){try{return 2<Se(a)?a.a.status:-1}catch(b){return-1}}; _.Ve=function(a){try{return a.a?a.a.responseText:""}catch(b){return""}};Vc(function(a){Ge.prototype.N=a(Ge.prototype.N)});
var Ze;_.N=function(a){_.F.call(this);this.T=a;this.J={}};_.p(_.N,_.F);var Ye=[];_.N.prototype.listen=function(a,b,c,d){_.Ca(b)||(b&&(Ye[0]=b.toString()),b=Ye);for(var e=0;e<b.length;e++){var f=_.ie(a,b[e],c||this.handleEvent,d||!1,this.T||this);if(!f)break;this.J[f.key]=f}return this};_.$e=function(a,b,c,d){Ze(a,b,c,d,void 0)};Ze=function(a,b,c,d,e,f){if(_.Ca(c))for(var h=0;h<c.length;h++)Ze(a,b,c[h],d,e,f);else(b=_.pe(b,c,d||a.handleEvent,e,f||a.T||a))&&(a.J[b.key]=b)};
_.N.prototype.Qa=function(a,b,c,d,e){if(_.Ca(b))for(var f=0;f<b.length;f++)this.Qa(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.T||this,c=je(c),d=!!d,b=Wd(a)?de(a.g,String(b),c,d,e):a?(a=le(a))?de(a,b,c,d,e):null:null,b&&(re(b),delete this.J[b.key]);return this};_.N.prototype.removeAll=function(){_.mb(this.J,function(a,b){this.J.hasOwnProperty(b)&&re(a)},this);this.J={}};_.N.prototype.w=function(){_.N.A.w.call(this);this.removeAll()};_.N.prototype.handleEvent=function(){throw Error("m");};
var af=function(){};af.prototype.c=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};var bf=function(a){(a?a:function(){}).Lb=!0};_.cf=function(){};_.p(_.cf,af);_.cf.prototype.b=function(a){return a};bf(_.cf.prototype.b);_.cf.prototype.g=function(){return!0};bf(_.cf.prototype.g);var df=function(a){_.z(this,a,0,null,null)};_.p(df,_.y);var ef;ef=function(a,b){var c=new df;_.B(c,1,b);_.B(c,2,a);return c};_.ff=ef("?",0);_.gf=ef("q",1);_.hf=ef("<",2);_.jf=ef(">",3);_.kf=ef("~",4);_.lf=ef("s",5);_.O=function(a,b,c){this.g=a;this.b=b||null;this.a=c||[]};_.O.prototype.toString=function(){return this.g};var mf,nf,pf,rf,sf,Bf,tf,vf,uf,yf,wf,of,Cf;
_.P=function(a,b){this.b=this.C=this.h="";this.c=null;this.l=this.a="";this.j=!1;var c;if(a instanceof _.P){this.j=_.m(b)?b:a.j;mf(this,a.h);this.C=a.C;this.b=a.b;nf(this,a.c);this.a=a.a;c=a.g;var d=new of;d.g=c.g;c.a&&(d.a=new _.J(c.a),d.b=c.b);pf(this,d);_.qf(this,a.l)}else a&&(c=String(a).match(Ee))?(this.j=!!b,mf(this,c[1]||"",!0),this.C=rf(c[2]||""),this.b=rf(c[3]||"",!0),nf(this,c[4]),this.a=rf(c[5]||"",!0),pf(this,c[6]||"",!0),_.qf(this,c[7]||"",!0)):(this.j=!!b,this.g=new of(null,0,this.j))};
_.P.prototype.toString=function(){var a=[],b=this.h;b&&a.push(sf(b,tf,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.C)&&a.push(sf(b,tf,!0),"@"),a.push((0,window.encodeURIComponent)(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.c,null!=c&&a.push(":",String(c));if(c=this.a)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(sf(c,"/"==c.charAt(0)?uf:vf,!0));(c=this.g.toString())&&a.push("?",c);(c=this.l)&&a.push("#",sf(c,wf));return a.join("")};
mf=function(a,b,c){a.h=c?rf(b,!0):b;a.h&&(a.h=a.h.replace(/:$/,""))};nf=function(a,b){if(b){b=Number(b);if((0,window.isNaN)(b)||0>b)throw Error("r`"+b);a.c=b}else a.c=null};pf=function(a,b,c){b instanceof of?(a.g=b,xf(a.g,a.j)):(c||(b=sf(b,yf)),a.g=new of(b,0,a.j))};_.R=function(a,b,c){a.g.set(b,c)};_.qf=function(a,b,c){a.l=c?rf(b):b};_.zf=function(a){return a instanceof _.P?new _.P(a):new _.P(a,void 0)};
_.Af=function(a,b){a instanceof _.P||(a=_.zf(a));b instanceof _.P||(b=_.zf(b));var c=a,d=b,e=new _.P(c),f=!!d.h;f?mf(e,d.h):f=!!d.C;f?e.C=d.C:f=!!d.b;f?e.b=d.b:f=null!=d.c;var h=d.a;if(f)nf(e,d.c);else if(f=!!d.a)if("/"!=h.charAt(0)&&(c.b&&!c.a?h="/"+h:(c=e.a.lastIndexOf("/"),-1!=c&&(h=e.a.substr(0,c+1)+h))),c=h,".."==c||"."==c)h="";else if(-1!=c.indexOf("./")||-1!=c.indexOf("/.")){for(var h=_.Ha(c,"/"),c=c.split("/"),k=[],n=0;n<c.length;){var q=c[n++];"."==q?h&&n==c.length&&k.push(""):".."==q?((1<
k.length||1==k.length&&""!=k[0])&&k.pop(),h&&n==c.length&&k.push("")):(k.push(q),h=!0)}h=k.join("/")}else h=c;f?e.a=h:f=""!==d.g.toString();f?pf(e,rf(d.g.toString())):f=!!d.l;f&&_.qf(e,d.l);return e};rf=function(a,b){return a?b?(0,window.decodeURI)(a.replace(/%25/g,"%2525")):(0,window.decodeURIComponent)(a):""};sf=function(a,b,c){return _.t(a)?(a=(0,window.encodeURI)(a).replace(b,Bf),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};
Bf=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};tf=/[#\/\?@]/g;vf=/[\#\?:]/g;uf=/[\#\?]/g;yf=/[\#\?@]/g;wf=/#/g;of=function(a,b,c){this.b=this.a=null;this.g=a||null;this.c=!!c};Cf=function(a){a.a||(a.a=new _.J,a.b=0,a.g&&Fe(a.g,function(b,c){var d=(0,window.decodeURIComponent)(b.replace(/\+/g," "));Cf(a);a.g=null;var d=Df(a,d),e=a.a.get(d);e||a.a.set(d,e=[]);e.push(c);a.b+=1}))};
of.prototype.remove=function(a){Cf(this);a=Df(this,a);return _.Nc(this.a,a)?(this.g=null,this.b-=this.a.get(a).length,this.a.remove(a)):!1};of.prototype.clear=function(){this.a=this.g=null;this.b=0};var Ef=function(a,b){Cf(a);b=Df(a,b);return _.Nc(a.a,b)};of.prototype.V=function(){Cf(this);for(var a=this.a.S(),b=this.a.V(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
of.prototype.S=function(a){Cf(this);var b=[];if(_.t(a))Ef(this,a)&&(b=_.hb(b,this.a.get(Df(this,a))));else{a=this.a.S();for(var c=0;c<a.length;c++)b=_.hb(b,a[c])}return b};of.prototype.set=function(a,b){Cf(this);this.g=null;a=Df(this,a);Ef(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};of.prototype.get=function(a,b){var c=a?this.S(a):[];return 0<c.length?String(c[0]):b};_.Ff=function(a,b,c){a.remove(b);0<c.length&&(a.g=null,a.a.set(Df(a,b),_.ib(c)),a.b+=c.length)};
of.prototype.toString=function(){if(this.g)return this.g;if(!this.a)return"";for(var a=[],b=this.a.V(),c=0;c<b.length;c++)for(var d=b[c],e=(0,window.encodeURIComponent)(String(d)),d=this.S(d),f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+(0,window.encodeURIComponent)(String(d[f])));a.push(h)}return this.g=a.join("&")}; var Df=function(a,b){var c=String(b);a.c&&(c=c.toLowerCase());return c},xf=function(a,b){b&&!a.c&&(Cf(a),a.g=null,a.a.forEach(function(a,b){var c=b.toLowerCase();b!=c&&(this.remove(b),_.Ff(this,c,a))},a));a.c=b};
_.cf.A||_.p(_.cf,af);_.Gf=function(a){switch(a){case 1:return"homepage";case 4:return"Google Translator Toolkit";case 5:return"Google Sites";case 6:return"customersupport";case 9:return"present";case 15:return"hangout";case 18:return"gmail";case 20:return"docs";case 24:return"docs_hangout";case 22:return"hangout_lite";case 23:return"aChromeExtension";case 25:return"bigtop";case 27:return"ChromeApp";case 36:return"StartPage"}};
_.Hf=function(a){_.z(this,a,"uv_r_rdm",null,null)};_.p(_.Hf,_.y);_.Hf.messageId="uv_r_rdm";_.If=function(a){_.z(this,a,"uv_r_rr",null,null)};_.p(_.If,_.y);_.If.messageId="uv_r_rr";_.Jf=function(a){_.z(this,a,"uv_r_frm",null,null)};_.p(_.Jf,_.y);_.Jf.messageId="uv_r_frm";_.Kf=function(a){_.z(this,a,0,null,null)};_.p(_.Kf,_.y);
var Mf=function(a,b){var c=Array.prototype.slice.call(arguments),d=c.shift();if("undefined"==typeof d)throw Error("t");return d.replace(/%([0\-\ \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(a,b,d,k,n,q,v,Z){if("%"==q)return"%";var e=c.shift();if("undefined"==typeof e)throw Error("u");arguments[0]=e;return Lf[q].apply(null,arguments)})},Lf={s:function(a,b,c){return(0,window.isNaN)(c)||""==c||a.length>=Number(c)?a:a=-1<b.indexOf("-",0)?a+Ta(" ",Number(c)-a.length):Ta(" ",Number(c)-a.length)+a},f:function(a,
b,c,d,e){d=a.toString();(0,window.isNaN)(e)||""==e||(d=(0,window.parseFloat)(a).toFixed(e));var f;f=0>Number(a)?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=Number(a)&&(d=f+d);if((0,window.isNaN)(c)||d.length>=Number(c))return d;d=(0,window.isNaN)(e)?Math.abs(Number(a)).toString():Math.abs(Number(a)).toFixed(e);a=Number(c)-d.length-f.length;return d=0<=b.indexOf("-",0)?f+d+Ta(" ",a):f+Ta(0<=b.indexOf("0",0)?"0":" ",a)+d},d:function(a,b,c,d,e,f,h,k){return Lf.f((0,window.parseInt)(a,10),b, c,d,0,f,h,k)}};Lf.i=Lf.d;Lf.u=Lf.d;
_.S=function(a,b){for(var c=[],d=0;d<arguments.length;d++)if(arguments[d]instanceof Error)c.push(arguments[d].stack);else if("object"==typeof arguments[d])try{c.push(JSON.stringify(arguments[d]))}catch(e){c.push("_error_("+e+")")}else c.push(arguments[d]);window.console&&(d=new Date,d=Mf("%02d-%02d ",d.getMonth()+1,d.getDate())+d.toLocaleTimeString()+Mf(".%03d",d.getMilliseconds()),window.console.log(d+" info: "+Mf.apply({},c)))};
_.Nf=new _.O("pVbxBc");_.T=new _.O("nED8Yb");_.Of=new _.O("xclgJb");_.Pf=new _.O("Qz9Lj");_.Rf=function(a){_.z(this,a,"h_exts",Qf,null)};_.p(_.Rf,_.y);var Qf=[2];_.Rf.messageId="h_exts";_.Sf=function(a){return _.Af(a,"/webchat/host-js")};_.Tf=function(a){var b=_.Sf(_.A(a,2));_.R(b,"prop",_.Gf(27));_.R(b,"b",1);_.R(b,"hl",_.A(a,3));_.A(a,4)&&_.R(b,"jsmode",_.A(a,4));_.R(b,"zx",_.Va());return b.toString()};var Uf;Uf=function(a){return(a=a.exec(_.jb))?a[1]:""};_.Vf=function(){if(Sb)return Uf(/Firefox\/([0-9.]+)/);if(_.x||Bb||Ab)return Nb;if(Wb)return Uf(/Chrome\/([0-9.]+)/);if(Xb&&!(ub()||_.w("iPad")||_.w("iPod")))return Uf(/Version\/([0-9.]+)/);if(Tb||Ub){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.jb);if(a)return a[1]+"."+a[2]}else if(Vb)return(a=Uf(/Android\s+([0-9.]+)/))?a:Uf(/Version\/([0-9.]+)/);return""}();
var Wf=function(a,b){_.K.call(this,a,b);this.P=b};_.p(Wf,_.K);var Xf=function(a){_.z(this,a,"capi_md1571",null,null)};_.p(Xf,_.y);Xf.messageId="capi_md1571";var Yf={hb:0,wc:1,vc:2,gb:3,Sa:4},Zf=function(a){_.z(this,a,0,null,null)};_.p(Zf,_.y);var ag=function(){for(var a=10,b=$f,c=b.length,d="";0<a--;)d+=b.charAt(Math.floor(Math.random()*c));return d},$f="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";_.bg=function(a,b){_.F.call(this);this.j=b||ag();this.c=this.a="";this.b=this.g=null;this.l=a;this.h=new _.N(this);_.I(this,this.h);this.h.listen(window,"message",this.m)};_.p(_.bg,_.F);_.bg.prototype.ca=function(a,b,c){this.c=a;this.g=b;this.b=c};
_.bg.prototype.m=function(a){a=a.a;var b;b=a.origin;this.g&&this.g!=a.source||"*"!=this.c&&this.c!=b?b=!1:this.b?(b=(new _.P(b)).b,b=_.Ia(b,this.b)?b.length==this.b.length||"."==this.b[0]||"."==b[b.length-1-this.b.length]:!1):b=!0;if(b&&(b=a.data)&&_.t(b)&&"["==b[0]){var c;try{if(c=JSON.parse(b),!_.Ca(c))return}catch(d){return}if(0!=c.length&&"capi_md1571"==c[0]&&(c=new Xf(c),_.A(c,1)==this.j)){b=_.A(c,3);if(!this.a)this.a=b;else if(this.a!=b)return;"*"!=this.c&&this.g||this.ca(a.origin,a.source);
1==_.A(c,2)?this.send(2):this.l(c,a)}}};_.bg.prototype.send=function(a,b,c){if(this.a&&this.g){b=b||new Xf;_.B(b,3,this.j);_.B(b,1,this.a);_.B(b,2,a);var d=JSON.stringify(_.D(b)),e=this.g,f=this.c;_.x?_.Ce(function(){e.postMessage(d,f)}):c?e.postMessage(d,f,c):e.postMessage(d,f)}};
var cg=function(a,b,c,d,e){this.g=_.sd();this.a=new _.bg((0,_.r)(this.h,this),d);this.a.ca(a,b,e);this.a.a=c;this.b=new _.Be(50);this.b.start();_.ie(this.b,"tick",this.c,!1,this);this.c();a=this.g.a;b=this.j;b=pd(b,b,this);b.g=!0;zd(a,b)};cg.prototype.j=function(){_.H(this.a);_.qe(this.b,"tick",this.c,!1,this);_.H(this.b)};cg.prototype.c=function(){this.a.send(1)};cg.prototype.h=function(a,b){2==_.A(a,2)&&this.g.b(b.origin)};
var dg=function(a,b,c){_.F.call(this);this.b=a;a=_.A(b,3);b=_.A(b,1);this.a=new _.bg((0,_.r)(this.g,this),b);this.a.a=a;c&&this.a.ca(c.origin,c.source);_.I(this,this.a)};_.p(dg,_.F);dg.prototype.send=function(a){var b=new Xf;_.E(b,4,a);this.a.send(Yf.hb,b)};dg.prototype.connect=function(a,b){this.a.ca(a,b);this.a.send(Yf.gb)};dg.prototype.g=function(a){_.A(a,2)==Yf.hb&&(a=_.C(a,Zf,4),this.b(a))};dg.prototype.c=_.Da;
var fg=function(a,b,c){_.F.call(this);this.h=a;this.b=this.a=this.g=null;c?(this.b=c.ports[0],eg(this)):(this.a=new _.bg(_.Da,_.A(b,1)),a=_.A(b,3),this.a.a=a)};_.p(fg,_.F);fg.prototype.w=function(){fg.A.w.call(this);this.b&&this.b.close();_.H(this.a)};fg.prototype.c=function(){this.g=new _.N(this);_.I(this,this.g);eg(this)};fg.prototype.send=function(a){this.b.postMessage(_.D(a))};
fg.prototype.connect=function(a,b){var c=new window.MessageChannel;this.b=c.port1;eg(this);var d=this.a;this.a=null;c=c.port2;d.ca(a,b);d.send(Yf.Sa,void 0,[c]);_.H(d)};var eg=function(a){a.b&&a.g&&(a.g.listen(a.b,"message",a.j),a.b.start())};fg.prototype.j=function(a){a=a.a;var b;try{b=new Zf(a.data)}catch(c){return}this.h(b)};
var gg=function(a,b,c){var d=!1;_.m(_.A(b,2))?_.A(b,2)==Yf.Sa&&(d=!0):d=Wb;return d?new fg(a,b,c):new dg(a,b,c)};var kg;_.hg=function(){_.L.call(this);this.h=null;this.l=!1;this.j=[];this.c=[];_.G(this,this.o,this);this.b=null};_.p(_.hg,_.L);_.hg.prototype.o=function(){for(;this.c.length;)this.c.shift()()};_.jg=function(a){a.o();a.j=[];a.b=new _.Fd;a.c.push((0,_.r)(a.b.cancel,a.b));a.l=!1;_.Md(a.b.h(),function(a){(ee(this.g)||this.J)&&ig(this);this.c.push(_.xa(_.H,a))},a)};_.g=_.hg.prototype;_.g.sendMessage=function(a){this.ya(_.D(a))};_.g.ya=function(a){if(this.b){var b=new Zf;_.B(b,1,a);_.Md(this.b.h(),function(a){a.send(b)})}};
_.g.fb=function(a){this.h=a;_.G(this,function(){this.h=null},this);ig(this)};_.g.F=function(){return this};_.g.ca=function(a,b,c){this.a.ca(a,b,c)};_.lg=function(a,b,c,d){_.jg(a);kg(a,b,c,d).then(function(a){var d=new Xf;_.B(d,1,a.sc);_.B(d,3,c);d=gg((0,_.r)(this.m,this),d);d.connect(a.origin,b);this.b.b(d)},void 0,a)};kg=function(a,b,c,d){var e=ag();b=(new cg("*",b,c,e,d)).g.a;a.c.push((0,_.r)(b.cancel,b));return b.then(function(a){return{sc:e,origin:a}})};
_.hg.prototype.D=function(a,b){if(_.A(a,2)==Yf.gb||_.A(a,2)==Yf.Sa)_.H(this.a),this.a=null,this.b.b(gg((0,_.r)(this.m,this),a,b))};_.hg.prototype.m=function(a){this.j.push(a);this.v()};_.hg.prototype.v=function(){for(;mg(this););};var mg=function(a){if(a.I||!a.l||0==a.j.length)return!1;var b=_.A(a.j.shift(),1);a.h&&a.h.ya(b);_.M(a,new Wf(b[0],b));return!0},ig=function(a){a.l||(a.l=!0,a.b&&_.Md(a.b.h(),function(a){a.c();_.Ce(this.v,0,this)},a))}; _.hg.prototype.listen=function(a,b,c,d){ig(this);return _.hg.A.listen.call(this,a,b,c,d)};_.hg.prototype.Ma=function(a,b,c,d){ig(this);return _.hg.A.Ma.call(this,a,b,c,d)};_.hg.prototype.G=function(a){ig(this);return _.hg.A.G.call(this,a)};
var ng=function(a){this.b=a;this.c="empty";this.a=null;this.g={}};ng.prototype.setVersion=function(a){this.c=a;return this};ng.prototype.Oa=function(a){this.a=a;return this};ng.prototype.eb=function(a){this.g=_.qb(a);return this};var og=function(){};var pg=function(){};_.p(pg,og);pg.prototype.clear=function(){var a=Kc(this.ha(!0)),b=this;(0,_.u)(a,function(a){b.remove(a)})};var qg=function(a){this.a=a};_.p(qg,pg);_.g=qg.prototype;_.g.isAvailable=function(){if(!this.a)return!1;try{return this.a.setItem("__sak","1"),this.a.removeItem("__sak"),!0}catch(a){return!1}};_.g.set=function(a,b){try{this.a.setItem(a,b)}catch(c){if(0==this.a.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};_.g.get=function(a){a=this.a.getItem(a);if(!_.t(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};_.g.remove=function(a){this.a.removeItem(a)};
_.g.ha=function(a){var b=0,c=this.a,d=new Hc;d.next=function(){if(b>=c.length)throw Gc;var d=c.key(b++);if(a)return d;d=c.getItem(d);if(!_.t(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};_.g.clear=function(){this.a.clear()};_.g.key=function(a){return this.a.key(a)};
var rg=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.a=a};_.p(rg,qg);var tg=function(a,b){this.g=a;this.a=[];this.b=null;b&&(this.b=new rg);if(null!=this.b&&this.b.isAvailable()){var c=this.b.get("__webmonitoring_RateThrottler_history_hourlyRate");if(null!=c)try{this.a=$b(c)||[]}catch(d){}}c=!1;_.Ca(this.a)||(this.a=[],c=!0);for(;this.a.length>this.g;)this.a.shift(),c=!0;c&&sg(this)},sg=function(a){if(null!=a.b&&a.b.isAvailable())try{a.b.set("__webmonitoring_RateThrottler_history_hourlyRate",_.cc(a.a))}catch(b){}};
var ug=function(a){_.F.call(this);this.a=a;this.h=!1};_.p(ug,_.F);ug.prototype.setEnabled=function(a){this.h=a};var U=function(a){ug.call(this,a);this.o=100;this.m={};this.O=null;this.g="";this.J=!0;this.j=10;this.b=null;this.c=!1};_.p(U,ug);U.prototype.ub=function(a){this.J=a;return this};U.prototype.setUseLocalStorage=U.prototype.ub;U.prototype.qc=function(a){this.j=Math.min(a,100);return this};U.prototype.setMaxErrorsPerHour=U.prototype.qc;U.prototype.sb=function(a){this.o=a;return this};U.prototype.setGlobalSampling=U.prototype.sb;U.prototype.jb=function(a,b){this.m[a]=b;return this};
U.prototype.addPerErrorMessageSampling=U.prototype.jb;U.prototype.rb=function(a){this.O=a;return this};U.prototype.setCallback=U.prototype.rb;U.prototype.pc=function(a){this.g=a;return this};U.prototype.setClientId=U.prototype.pc;U.prototype.enable=function(){if(this.h)return!1;this.l=window.onerror;window.onerror=this.v.bind(this);this.setEnabled(!0);return!0};U.prototype.enable=U.prototype.enable;
U.prototype.ob=function(a,b,c,d,e){var f=_.zf(window.location.href);a=null!=e&&null!=e.message?e.message:a;var h;if(h=!_.za(this.O)||this.O(f.a,a,b,c,d,e))if(h=this.c){h=Object.keys(this.m);for(var k=100,n=0;n<h.length;++n){var q=h[n];(new RegExp(q)).test(a)&&(k=this.m[q])}if(h=(100*Math.random()).toFixed(6)>=this.o*k/100?!1:!0){0<=this.j&&null===this.b&&(this.b=new tg(this.j,this.J));if(null===this.b)h=0;else{a:{h=this.b;k=(0,_.sa)();if(h.a.length==h.g)if(h.a[0]<k-36E5)h.a.shift();else{h=!1;break a}h.a.push(k);
sg(h);h=!0}h=!h}h=!h&&this.c}}h&&(h=_.qb(this.a.g),h.url=f.a,h.type="JavascriptError",h.error_message=a,k="Other",Ab?k="Opera":_.x?k="Internet Explorer":Sb?k="Firefox":Wb?k="Chrome":Xb&&(k="Safari"),h.browser=k,h.browser_version=_.Vf,h.os=_.w("CrOS")?"Chrome OS":_.w("Linux")?"Linux":_.wb()?"Windows":_.w("Android")?"Android":ub()?"iPhone":_.w("iPad")?"iPad":_.w("iPod")?"iPod":_.vb()?"Mac":"Unknown",k=_.jb,n="",_.wb()?(n=/Windows (?:NT|Phone) ([0-9.]+)/,n=(k=n.exec(k))?k[1]:"0.0"):ub()||_.w("iPad")||
_.w("iPod")?(n=/(?:iPhone|iPod|iPad|CPU)\s+OS\s+(\S+)/,n=(k=n.exec(k))&&k[1].replace(/_/g,".")):_.vb()?(n=/Mac OS X ([0-9_.]+)/,n=(k=n.exec(k))?k[1].replace(/_/g,"."):"10"):_.w("Android")?(n=/Android\s+([^\);]+)(\)|;)/,n=(k=n.exec(k))&&k[1]):_.w("CrOS")&&(n=/(?:CrOS\s+(?:i686|x86_64)\s+([0-9.]+))/,n=(k=n.exec(k))&&k[1]),h.os_version=n||"",null!=this.a.a&&(h.channel=this.a.a),_.Ja(this.g)||(h.guid=this.g),null!=b&&(h.src=b),null!=c&&(h.line=c),null!=d&&(h.column=d),h.prod=this.a.b,h.ver=this.a.c,b=
vg(h),e=null!=e?_.Ua(e.stack):"",_.Ja(a)||(c=e.split("\n"),-1<c[0].indexOf(a)&&(c.splice(0,1),e=c.join("\n"))),wg(this,"https://clients2.google.com/cr/staging_report",b,e),f={product:this.a.b,url:f.a,js_errors_count:"1"},a=_.Ua(this.a.a),_.Ja(a)||(f.version=a),wg(this,"https://clients2.google.com/cr/staging_perf",vg(f)))};U.prototype.reportError=U.prototype.ob;U.prototype.v=function(a,b,c,d,e){this.ob(a,b,c,d,e);null!=this.l&&_.za(this.l)&&this.l(a,b,c,d,e)};
var vg=function(a){var b="",c;for(c in a)b+=_.Ja(b)?"?":"&",b+=c+"="+(0,window.encodeURIComponent)(a[c]);return b},wg=function(a,b,c,d){d=d||"";var e=_.Ja(d)?{}:{"Content-Type":"text/plain"};_.Ke(b+c,a.G.bind(a,b),"POST",d,e,6E4,!0)};U.prototype.G=function(a,b){_.Ue(b.target)};
var xg=function(a){ug.call(this,a);this.O=null;this.b=0};_.p(xg,ug);xg.prototype.rb=function(a){this.O=a;return this};var yg=[{age:6E4,name:"1m"},{age:15E5,name:"25m"},{age:36E5,name:"1h"},{age:36E6,name:"10h"}];xg.prototype.enable=function(){if(this.h)return!1;if(window.performance&&window.performance.memory){var a=new _.Be(6E4);_.I(this,a);var b=new _.N(this);_.I(this,b);b.listen(a,"tick",this.g);a.start();this.setEnabled(!0);return!0}return!1};
xg.prototype.g=function(){this.b+=6E4;for(var a="",b=0;b<yg.length;++b)if(this.b==yg[b].age){a=yg[b].name;break}if(""!=a){var b=zg.test(_.jb)?"":"32_bit_",c=window.performance.memory;if(c.totalJSHeapSize&&c.usedJSHeapSize){var a=[{name:"total_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Total JS heap (MB)",value:Math.round(c.totalJSHeapSize/1048576)},{name:"used_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Used JS heap (MB)",value:Math.round(c.usedJSHeapSize/1048576)}],b=_.zf(window.location.href).a,
c="?product="+(0,window.encodeURIComponent)(this.a.b)+"&url="+(0,window.encodeURIComponent)(b),d=_.Ua(this.a.a);_.Ja(d)||(c+="&version="+(0,window.encodeURIComponent)(d));for(d=0;d<a.length;++d)c+="&"+(0,window.encodeURIComponent)(a[d].name)+"="+a[d].value,_.za(this.O)&&this.O(b,a[d].displayName,a[d].value);_.Ke("https://clients2.google.com/cr/staging_perf"+c,Ag,"POST","",null,6E4,!0)}}};var Ag=function(a){_.Ue(a.target)},zg=/(x86_64|Win64)/;
var Bg=function(a){_.F.call(this);this.b=new ng(a);this.a={}};_.p(Bg,_.F);_.wa("webmonitoring.Monitoring",Bg);Bg.prototype.setVersion=function(a){this.b.setVersion(a);return this};Bg.prototype.setVersion=Bg.prototype.setVersion;Bg.prototype.Oa=function(a){this.b.Oa(a);return this};Bg.prototype.setChannel=Bg.prototype.Oa;Bg.prototype.eb=function(a){this.b.eb(a);return this};Bg.prototype.setContext=Bg.prototype.eb;Bg.prototype.Ka=function(){null!=this.a[2]||(this.a[2]=new U(this.b));return this.a[2]}; Bg.prototype.createJsErrorsReporter=Bg.prototype.Ka;
var Cg=function(a){Bg.call(this,a)};_.p(Cg,Bg);Cg.prototype.Ka=function(){var a=Cg.A.Ka.call(this);a.c=!0;return a};_.Dg=function(){var a=new Cg("Google_Hangouts_Chrome");a.Oa(window.chrome.runtime.id);a.setVersion(window.chrome.runtime.getManifest().version);null!=a.a[1]||(a.a[1]=new xg(a.b));a.a[1].enable();a.Ka().ub(!1).sb(100).jb("Script error.",0).enable()};var Eg=function(a,b){this.g=a;this.b=b;this.constructor.kb||(this.constructor.kb={});this.constructor.kb[this.toString()]=this};Eg.prototype.toString=function(){this.a||(this.a=this.g.a+":"+this.b);return this.a};var Fg=function(a,b){Eg.call(this,a,b)};_.p(Fg,Eg);var Gg=function(a){this.a=a};new Gg("lib");var Hg,Pg,Qg,Rg;_.Ig=function(a){_.F.call(this);this.c={};this.j={};this.l={};this.a={};this.g={};this.G={};this.m=a?a.F():new _.L;this.N=!a;this.b=null;a?(this.b=a,this.l=a.l,this.a=a.a,this.j=a.j,this.g=a.g):(0,_.sa)();a=Hg(this);this!=a&&(a.h?a.h.push(this):a.h=[this])};_.p(_.Ig,_.F);_.Jg=.05>Math.random();Hg=function(a){for(;a.b;)a=a.b;return a};_.Ig.prototype.get=function(a){var b=_.Kg(this,a);if(null==b)throw new Lg(a);return b};
_.Kg=function(a,b){for(var c=a;c;c=c.b){if(c.I)throw Error("v");if(c.c[b])return c.c[b][0];if(c.G[b])break}if(c=a.l[b]){c=c(a);if(null==c)throw Error("w`"+b);_.Mg(a,b,c);return c}return null};
_.Ig.prototype.J=function(a,b){var c=_.Kg(this,a);if(null==c){if(this.g[a]){var d=this.g[a].h();_.Md(d,(0,_.r)(this.J,this,a,b));return d}throw new Ng(a,b,"Module loaded but service or factory not registered with app contexts.");}return c.Wa?(d=new _.Fd,_.Nd(d,c.Wa()),d.b(c),_.Md(d,(0,_.r)(this.o,this,a)),d):this.o(a)};_.Ig.prototype.o=function(a){this.g[a]&&delete this.g[a];return this.get(a)};_.Ig.prototype.H=function(a,b,c){return c instanceof _.Gd?c:new Og(a,b,c)};
_.Mg=function(a,b,c,d){if(a.I)d||_.H(c);else{a.c[b]=[c,!d];d=Pg(a,a,b);for(var e=0;e<d.length;e++)d[e].b(null);delete a.j[b];return c}};Pg=function(a,b,c){var d=[],e=a.a[c];e&&(_.Za(e,function(a){var c;a:{for(c=a.Va;c;){if(c==b){c=!0;break a}c=c.b}c=!1}c&&(d.push(a.d),_.gb(e,a))}),0==e.length&&delete a.a[c]);return d};Qg=function(a,b){a.a&&Pc(a.a,function(a,d,e){_.Za(a,function(c){c.Va==b&&_.gb(a,c)});0==a.length&&delete e[d]})};
_.Ig.prototype.D=function(a,b){var c=this.a&&this.a[a];if(c){for(var d=0;d<c.length;++d)if(c[d].Va==this&&c[d].d==b){_.fb(c,d);break}0==c.length&&delete this.a[a]}};_.Ig.prototype.w=function(){if(Hg(this)==this){var a=this.h;if(a)for(;a.length;)a[0].$()}else for(var a=Hg(this).h,b=0;b<a.length;b++)if(a[b]==this){a.splice(b,1);break}for(var c in this.c)a=this.c[c],a[1]&&a[0].$&&a[0].$();this.c=null;this.N&&this.m.$();Qg(this,this);this.a=null;_.H(this.M);this.G=this.M=null;_.Ig.A.w.call(this)};
_.Ig.prototype.F=function(){return this.m};var Lg=function(a){_.Fa.call(this);this.id=a;this.message='Service for "'+a+'" is not registered'};_.p(Lg,_.Fa);var Og=function(a,b,c){_.Fa.call(this);this.message='Module "'+b+'" failed to load when requesting the service "'+a+'" [cause: '+c+"]";this.stack=c.stack+"\nWRAPPED BY:\n"+this.stack};_.p(Og,_.Fa);var Ng=function(a,b,c){_.Fa.call(this);this.message='Configuration error when loading the module "'+b+'" for the service "'+a+'": '+c};_.p(Ng,_.Fa); Rg=new Gg("fva");_.Sg=new Fg(Rg,1);

}catch(e){_._DumpException(e)}
try{
var Bp=/\s*;\s*/,Cp=function(){return[]},Dp=function(a){a=(a.a.cookie||"").split(Bp);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}},Ep=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.a[c[0]];return d?d[a].apply(this.a[c[0]],arguments):this.aa[c[0]].prototype[a].apply(this,arguments)}:b[a].Nb?e=function(b){var d;a:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var f=
this.a[c[e]];if(f=f?f[a].apply(f,d):this.aa[c[e]].prototype[a].apply(this,d)){d=f;break a}}d=!1}return d}:b[a].Mb?e=function(b){var d;a:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var f=this.a[c[e]],f=f?f[a].apply(f,d):this.aa[c[e]].prototype[a].apply(this,d);if(null!=f){d=f;break a}}d=void 0}return d}:b[a].bc?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var f=this.a[c[e]];f?f[a].apply(f,d):this.aa[c[e]].prototype[a].apply(this,d)}}:
e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],f=0;f<c.length;++f){var q=this.a[c[f]];e.push(q?q[a].apply(q,d):this.aa[c[f]].prototype[a].apply(this,d))}return e}:d||b[a].Nb||b[a].Mb||b[a].bc?e=null:e=Cp;return e},Fp=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||(e.push(f),!d));++f);return e},Gp=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.Ba(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var h=0;h<f;h++)a[e+h]=d[h]}else a.push(d)}},
Hp=[1],Ip=function(a,b){return a.g.get(b)},Jp=function(a){this.a=a||{cookie:""}};_.g=Jp.prototype;_.g.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("p`"+a);if(/[;\r\n]/.test(b))throw Error("q`"+b);_.m(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,_.sa)()+1E3*c)).toUTCString();this.a.cookie=a+"="+b+e+d+c+f};
_.g.get=function(a,b){for(var c=a+"=",d=(this.a.cookie||"").split(Bp),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};_.g.remove=function(a,b,c){var d=_.m(this.get(a));this.set(a,"",0,b,c);return d};_.g.V=function(){return Dp(this).keys};_.g.S=function(){return Dp(this).values};_.g.clear=function(){for(var a=Dp(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};var Kp=function(a){return this.Za.c(a)},Lp=function(a){_.z(this,a,"ci:ec",null,null)};
_.p(Lp,_.y);Lp.messageId="ci:ec";
var Mp={a:_.ff,J:_.gf,m:_.hf,o:_.jf,l:_.kf,G:_.lf},Np=function(a){var b=a.na,c=function(a){c.A.constructor.call(this,a);var b=this.aa.length;this.a=[];for(var d=0;d<b;++d)this.aa[d].Fc||(this.a[d]=new this.aa[d](a))};_.p(c,b);for(var d=[];a;){if(b=a.na){b.aa&&Gp(d,b.aa);var e=b.prototype,f;for(f in e)if(e.hasOwnProperty(f)&&_.za(e[f])&&e[f]!==b){var h=!!e[f].Lb,k=Fp(f,e,d,h);(h=Ep(f,e,k,h))&&(c.prototype[f]=h)}}a=a.A&&a.A.constructor}c.prototype.aa=d;return c},Op=function(a){_.z(this,a,"capi:r_rstr",
null,null)};_.p(Op,_.y);Op.messageId="capi:r_rstr";var Pp=function(a){_.z(this,a,"capi:r_recl",null,null)};_.p(Pp,_.y);Pp.messageId="capi:r_recl";var Qp=function(a){_.z(this,a,"capi:r_clre",null,null)};_.p(Qp,_.y);Qp.messageId="capi:r_clre";var Rp=function(a){_.z(this,a,0,Hp,null)};_.p(Rp,_.y);var Sp=function(a){_.z(this,a,"uv_r_hrd",null,null)};_.p(Sp,_.y);Sp.messageId="uv_r_hrd";var Tp=function(a){_.z(this,a,"uv_r_rrr",null,null)};_.p(Tp,_.y);Tp.messageId="uv_r_rrr";
var Up=function(a){_.z(this,a,"uv_r_rdr",null,null)};_.p(Up,_.y);Up.messageId="uv_r_rdr";
var Vp=function(a,b,c){if(!this.Za){for(var d=this.constructor;d&&!d.na;)d=d.A&&d.A.constructor;d.na.mb||(d.na.mb=Np(d));this.Za=new d.na.mb(this);this.c||(this.c=Kp)}var e=this.Za.b(a.clientBaseUrl||"https://talkgadget.google.com/talkgadget/");if(_.Ha(e,"https://talkgadget.google.com/talkgadget/")){var d=(new Jp(window.document)).get("WCSDBG",""),d=d.split(";")[0],d=d.split("|")[0],f=["plus.google.com"],h=/^[-_a-zA-Z0-9\.]+\.talkgadget\.google\.com$/;0<d.length&&!_.eb(f,d)&&h.test(d)&&(e=_.zf(e),
e=_.zf("https://"+d+e.a).toString())}this.la=e;this.g=c||new Lp;a.notificationsOnly&&_.B(this.g,1,!0);this.b="0";null!=a.authUser?this.b=a.authUser:(c=Ip(new _.P(window.location.href),"authuser"),null!=c&&(this.b=c));this.m=a.clientUrl||"notifierclient";c=Ip(_.zf(this.m),"authuser");null!=c&&(this.b=c);this.Ta=a.propertyName||"Google Talk";this.J=a.cssUrl;this.locale=a.locale;this.C=a.debug;this.Ia=a.userJid;this.Fa=a.uiVersion;this.Vb=null!=a.rosterExpanded?a.rosterExpanded:!0;this.X=a.hostLogMinValue;
this.va=a.hideChat;this.Ob=a.refresh;this.M=a.hideProfileCard;this.U=a.hideStatusMsgs;this.T=a.hideRosterOptions;this.N=a.hideRecentConversations;this.K=a.hideOTR;this.Ua=a.hostServerMessageCallback||!1;this.Z=a.isCentralRoster;this.Ya=a.isFullFrame||!1;this.Ub=a.rosterClass||"talk_roster";this.Xb=a.rosterId||"talk_roster";this.a="gtn-roster-iframe-id";a.rosterFrameId&&a.rosterFrameId.match(/[\w-]/)&&(this.a=a.rosterFrameId);a.rosterIframeIdB&&a.rosterIframeIdB.match(/[\w-]/);this.ua=a.parentToken;
this.Rb=b||!1;this.h=_.m(a.isRtl)?a.isRtl:_.qc.test(this.locale);this.position=a.position||"l";if(!a.keyboardShortcuts){b=[];for(var k in Mp)b.push(_.D(Mp[k]))}this.v=a.entityId;this.Ga=a.useQuasarPanels||!1;this.wa=a.silent||!1;this.Xa=a.ignoreCentralRoster||!1;this.Qb=a.lazy||!1;this.Ra=a.handleProfileLinks||!1;this.Y=a.hostSettings;this.l=a.screen;this.G=a.docsConfig;this.Pb=a.jsmode;this.ta=a.moleWidth;this.ga=a.moleHeight;this.fa=a.minimizedMoleHeight||36;this.Yb=a.derp;this.Ea=window.location.protocol+
"//"+window.location.host;this.j="";this.H=a.optOutAllowed;this.D=a.legacyTalkSignedIn;this.Ha=a.useSpareMole;this.o=a.conversationId};Vp.na=_.cf;var Wp=function(a){_.z(this,a,0,null,null)};_.p(Wp,_.y);var Xp=function(a){_.z(this,a,0,null,null)};_.p(Xp,_.y);var Yp=function(a){_.z(this,a,0,null,null)};_.p(Yp,_.y);var Zp=function(a){_.z(this,a,0,null,null)};_.p(Zp,_.y);var $p=function(a){_.z(this,a,"h_cc",null,null)};_.p($p,_.y);$p.messageId="h_cc";
var aq=function(a,b){_.td(a,null,b,void 0)},bq=function(a,b,c){_.Ad(a,b,c,null)||_.hd(_.xa(b,a))},cq=function(a){return new _.md(function(b,c){var d=a.length,e=[];if(d)for(var f=function(a,c){d--;e[a]=c;0==d&&b(e)},h=function(a){c(a)},k=0,n;k<a.length;k++)n=a[k],bq(n,_.xa(f,k),h);else b(e)})};
var dq=function(a){this.a=a;_.x||(delete this.a.lpu,delete this.a.ppu)},eq=["cn","tp"],fq=function(a,b){var c;if(_.za(window.document.postMessage)||_.za(window.postMessage)||_.x&&window.postMessage)c=1;else if(_.Cb)c=2;else{var d;if(d=_.x){d=!1;try{c=window.opener,window.opener={},d=_.yb(window,"opener"),window.opener=c}catch(e){}}c=d?6:4}d={};d.cn=Math.floor(2147483648*Math.random()).toString(36);d.tp=c;d.ifrid=b;d.pu=a;return new dq(d)};_.wa("GTalk_IFrameChannelConfig.build",fq);
var gq=function(a,b,c,d,e){_.F.call(this);this.a=a;this.b=d||window.document;this.g=new _.N(this);_.I(this,this.g);var f=_.jb;d=new _.P(a.la+a.m);_.jc(a.g,2,!1)||(_.R(d,"ts","0"),_.R(d,"re",a.Vb),_.R(d,"ref",a.Ob));_.R(d,"client","sm");_.R(d,"prop",a.Ta);_.R(d,"nav","true");_.R(d,"fid",a.a);a.C&&_.R(d,"debug",a.C);_.R(d,"os",_.Fb);_.R(d,"stime",c);a.va&&_.R(d,"hc",a.va);for(c=0;c<eq.length;++c);b=_.cc(b.a);_.R(d,"xpc",b);_.R(d,"ec",_.cc(_.D(a.g)));a.l&&_.R(d,"screen",a.l);-1!=f.indexOf("MSIE")&&_.R(d,
"ua",f);a.ua&&_.R(d,"pvt",a.ua);a.Ua&&_.R(d,"hsmc","true");_.m(a.X)&&_.R(d,"logl",a.X);b=window.location.href;0>b.indexOf("?rel=1")&&(b=b.split("?"),b[1]=1==b.length?"rel=1":["rel=1&",b[1]].join(""),_.R(d,"href",b.join("?")));b=new _.P(window.location.href);"false"==Ip(b,"uacheck")&&_.R(d,"uacheck",!1);(f=a.Pb)&&_.R(d,"jsmode",f);(f=Ip(b,"cssmode"))&&_.R(d,"cssmode",f);(f=Ip(b,"convid"))&&_.R(d,"convid",f);if(f=b.g.S("convp"))_.Ca(f)||(f=[String(f)]),_.Ff(d.g,"convp",f);(f=Ip(b,"smexp"))&&_.R(d,"smexp",
f);f=b.g.S("mods");a.Qb&&f.push("lazy");e&&(f=_.hb(f,e));0<f.length&&_.R(d,"mods",f.join(","));if(!a.la||0>a.la.indexOf("/u/"))(e=Ip(b,"authuser"))?_.R(d,"authuser",e):null!=a.b&&_.R(d,"authuser",a.b);e=Ip(b,"eid");_.Ja(_.Ua(e))||_.R(d,"eid",e);_.Ja(_.Ua(this.a.v))||_.R(d,"eid",this.a.v);null!=this.a.position&&_.R(d,"pos",this.a.position);_.m(a.Fa)&&_.R(d,"uiv",this.a.Fa);a.J&&_.R(d,"css",a.J);e=a.locale||Ip(b,"hl");null!=e&&_.R(d,"hl",e);_.m(a.Ia)&&_.R(d,"uj",a.Ia);null!=a.M&&_.R(d,"hpc",a.M);null!=
a.U&&_.R(d,"hsm",a.U);null!=a.T&&_.R(d,"hro",a.T);null!=a.N&&_.R(d,"hrc",a.N);null!=a.K&&_.R(d,"hotr",a.K);null!=a.Z&&_.R(d,"pop",a.Z);a.Rb&&_.R(d,"pal","1");null!=a.Ga&&_.R(d,"uqp",a.Ga);null!=a.H&&_.R(d,"gooa",a.H);null!=a.D&&_.R(d,"gltsi",a.D);null!=a.Ha&&_.R(d,"gusm",a.Ha);null!=a.wa&&_.R(d,"sl",a.wa);a.Xa&&_.R(d,"icr","1");a.Ra&&_.R(d,"hpl","1");a.Y&&_.R(d,"hs",a.Y);a.G&&_.R(d,"dc",_.cc(_.D(a.G)));null!=a.ta&&_.R(d,"molew",a.ta);null!=a.ga&&_.R(d,"moleh",a.ga);null!=a.fa&&_.R(d,"mmoleh",a.fa);
a.Yb&&_.R(d,"derp","1");a.j&&_.R(d,"fcho",a.j);null!=a.Ea&&_.R(d,"two",a.Ea);null!=a.o&&_.R(d,"convid",a.o);_.R(d,"host","1");_.R(d,"zx",_.Va());this.c=d.toString()};_.p(gq,_.F);
var hq=function(a,b,c,d){var e=a.b.getElementById(b);e||(e=a.b.createElement("div"),e.id=b,e.className=a.a.Ub,a.b.body.appendChild(e));a=(0,_.r)(function(){var a="";this.a.Ya||(a="height:400px");var b=this.b.createElement("iframe");_.Bc(b,{id:this.a.a,name:this.a.a,"class":"talk_iframe",frameborder:"0",style:a,"aria-hidden":"true"});_.zc("talk_loading_msg",e)||_.Ec(e);e.appendChild(b);var k=this.b.getElementById(this.a.a);_.$e(this.g,k,["load","error"],function(a){k.contentWindow.postMessage("AllowFrame: Chat", "*");d(a)});k.src=this.c.toString();c()},a);window.setTimeout(a,0)};
var iq=new _.O("q"),jq=new _.O("r");var kq=function(a){_.L.call(this);this.a=a.get(jq);a=new _.N(this);_.I(this,a);a.listen(this.a.F(),"uv_r_frm",this.b);a.listen(this.a.F(),"uv_r_rdm",this.c)};_.p(kq,_.L);kq.prototype.reload=function(a){var b=new _.If;_.B(b,1,a);this.a.sendMessage(b)};kq.prototype.b=function(a){a=new _.Jf(a.P);_.M(this,new lq(!!_.A(a,1)))};kq.prototype.c=function(a){a=new _.Hf(a.P);_.M(this,new mq(_.A(a,1)))};var lq=function(a){_.K.call(this,"uv_r_frm");this.a=a};_.p(lq,_.K); var mq=function(a){_.K.call(this,"uv_r_rdm");this.a=a};_.p(mq,_.K);
var nq=function(a){var b=_.l.GTalkNotifier;return b?_.qd(b):new _.md(function(c,d){var e=_.Ce(function(){return d("chat.host.Client is not available!")},25E3),f=window.document.createElement("SCRIPT");f.src=_.Tf(a);f.addEventListener("load",function(){_.De(e);(b=_.l.GTalkNotifier)?c(b):d("chat.host.Client is not available!")});f.addEventListener("error",function(){_.De(e);d("chat.host.Client is not available!")});window.document.body.appendChild(f)})};
var oq=function(a){_.L.call(this);this.a=a.get(_.T);a=new _.N(this);_.I(a,a);a.listen(this.a.F(),"capi:r_clre",this.h);a.listen(this.a.F(),"capi:r_rrst",this.b);a.listen(this.a.F(),"capi:r_rers",this.c)};_.p(oq,_.L);oq.prototype.h=function(a){a=new Qp(a.P);_.M(this,new pq(_.C(a,Rp,1)))};oq.prototype.c=function(){_.M(this,"I")};oq.prototype.b=function(){_.M(this,"H")};var pq=function(a){_.K.call(this,"G");this.a=a};_.p(pq,_.K);
var qq=function(a){_.N.call(this);this.b=a.get(_.Pf);this.a=a.get(iq);this.listen(this.a,"uv_r_rdm",this.Jb);this.listen(this.a,"uv_r_frm",this.Ib);this.listen(this.b,"G",this.kc);this.listen(this.b,"H",this.Hb);this.listen(this.b,"I",this.Kb)};_.p(qq,_.N);_.g=qq.prototype;_.g.kc=function(a){a=(a=a.a)?[_.D(a)]:[void 0];this.a.reload(a)};_.g.Hb=function(){var a=this.a,b=new Up;a.a.sendMessage(b)};_.g.Ib=function(a){var b=this.b;a=!!a.a;var c=new Pp;_.B(c,1,!!a);b.a.sendMessage(c)}; _.g.Jb=function(a){if(a.a&&(a=a.a[0])){a=new Rp(a);var b=this.b,c=new Op;_.E(c,1,a);b.a.sendMessage(c)}};_.g.Kb=function(){var a=this.a,b=new Tp;a.a.sendMessage(b)};
var rq=function(a){return new _.md(function(b,c){_.Ke(_.Af(a,"/webchat/extension-start"),function(a){_.Ue(a.target)||c();try{var d=JSON.parse(_.Ve(a.target));b(new _.Rf(d))}catch(f){c(f.message)}})})};var sq=function(a){_.K.call(this,a[0]);this.P=a};_.p(sq,_.K);var uq=function(a,b){_.F.call(this);this.m=(0,_.sa)();var c={},d=_.jc(a,1,"hangouts.google.com"),e="";0>d.indexOf("://")&&(e="https://",0<=d.indexOf(":")&&23!=_.A(a,2)&&27!=_.A(a,2)&&(e="http://"));-1!=d.indexOf("talkgadget.")?(c.clientBaseUrl=e+d+"/talkgadget/_/",c.clientUrl="chat"):(c.clientBaseUrl=e+d+"/webchat/u/"+_.jc(a,8,"0")+"/",c.clientUrl="load");c.authUser=_.jc(a,8,"0");c.propertyName=_.Gf(_.A(a,2));c.locale=_.A(a,4);c.hideProfileCard=!0;c.parentToken=_.A(a,3);c.isRtl=_.jc(a,6,!1);c.lazy=
_.jc(a,7,!1);c.entityId=_.A(a,9);c.hostSettings=_.A(a,5);c.jsmode=_.A(a,11);c.isFullFrame=_.jc(a,13,!1);c.rosterId=_.jc(a,12,"talk_roster");c.rosterIframeIdB=_.jc(a,15,"gtn-roster-iframe-id-b");c.derp=!!_.jc(a,16,!1);d=_.C(a,Wp,14);null!=d&&(c.isCentralRoster=_.jc(d,1,!1),c.useQuasarPanels=_.jc(d,2,!1));d=_.C(a,Zp,10);null!=d&&(c.moleManagerLeftMargin=_.A(d,1),c.moleManagerMiddleMargin=_.A(d,2),c.moleManagerRightMargin=_.A(d,3),c.moleManagerNoMoleAreaMargin=_.A(d,4),c.moleManagerBoundingElementId=
_.A(d,5),c.moleWidth=_.A(d,6),c.moleHeight=_.A(d,7),c.minimizedMoleHeight=_.A(d,8));d=_.C(a,Yp,18);null!=d&&(c.optOutAllowed=_.jc(d,1,!0),e=_.C(d,Xp,3),null!=e&&(c.legacyTalkSignedIn=_.jc(e,1,!0)),d=_.A(d,4),null!=d&&(c.useSpareMole=d));c.uiVersion=2;c.hideStatusMsgs=!0;c.hideRecentConversations=!0;d=new Lp;_.B(d,2,!0);_.B(d,1,!0);_.B(d,3,!1);c.endpointConfig=d;c.ignoreAutomatedRoster=_.jc(a,17,!1);c.conversationId=_.A(a,19);this.c=c;c=this.a=new Vp(this.c,!0,this.c.endpointConfig);var f=this.a.la,
d=this.a.b;if(-1!=f.indexOf("talkgadget.")){var e=_.zf(f),h=e.a;if(0<=h.indexOf("/u/"))d=f;else{f=h.lastIndexOf("_/");if(0>f||f!=h.length-2)h+="_/";e.a="/u/"+d+h;d=e.toString()}}else d=f;c.la=d;this.a.j=window.location.origin;this.b=null;this.l=new _.L;c=_.qb(this.c);c.endpointConfig=_.D(this.a.g);this.h=new b(c,!0);this.j=new _.hg;_.I(this,this.j);tq(this)};_.p(uq,_.F);uq.prototype.sendMessage=function(a){this.ya(_.D(a))};uq.prototype.ya=function(a){this.g("_h",a)};
uq.prototype.fb=function(a){this.b=a;_.G(this,function(){this.b=null},this)};uq.prototype.F=function(){return this.l};var tq=function(a){var b=fq(a.a.la,a.a.a),b=new gq(a.a,b,a.m,window.document);_.I(a,b);hq(b,a.a.Xb,function(){},function(){return vq(a)})},vq=function(a){_.lg(a.j,window.document.getElementById(a.a.a).contentWindow,"31ACFC0_","google.com");a.g("_addClientMessageCallback",function(b){a.b&&a.b.ya(b);_.M(a.l,new sq(b))});a.g("_rosterIframeLoaded")}; uq.prototype.g=function(a,b){for(var c=[],d=1;d<arguments.length;d++)c.push(arguments[d]);this.h[a]&&this.h[a].apply(this.h,c)};
var xq=function(){_.N.call(this);_.S("Starting ...");this.a=new _.Ig;_.I(this,this.a);this.h=null;this.c=[];this.listen(window,"unload",this.$);this.b=new _.Kf(JSON.parse((0,window.decodeURI)(window.location.hash.substr(1))));var a=_.A(this.b,1),b=new _.hg;_.jg(b);b.a=new _.bg((0,_.r)(b.D,b),a);b.a.ca("*",void 0,void 0);b.c.push(_.xa(_.H,b.a));this.g=b;_.Mg(this.a,jq,this.g);wq(this)},yq;_.p(xq,_.N);
var wq=function(a){_.S("Initializing ...");aq(cq([rq(_.A(a.b,2)).then(a.j,void 0,a),nq(a.b)]).then(function(b){_.ga();var c=b[window.Symbol.iterator];b=c?c.call(b):_.fa(b);var d=b.next().value;b=b.next().value;if(a.I)b=null;else{var c=new $p,e=_.zf(_.A(a.b,2)),f=e.b;null!=e.c&&(f+=":"+e.c);_.B(c,1,f);_.B(c,2,27);_.B(c,13,!0);_.B(c,17,!0);d=_.A(d,1);_.B(c,3,d);d=_.A(a.b,4);_.B(c,11,d);d=_.A(a.b,3)||"en";_.B(c,4,d);d=new Wp;_.B(d,2,!0);_.B(d,1,!0);_.E(c,14,d);b=new uq(c,b)}return b}).then(function(b){if(!a.I){b.fb(a.g);
a.g.fb(b);a.h=b;_.Mg(a.a,_.T,a.h);b=new kq(a.a);_.Mg(a.a,iq,b);_.Mg(a.a,_.Pf,new oq(a.a));new qq(a.a);for(a.g.sendMessage(new Sp);a.c.length;)a.c.shift()();a.c=null}}),function(a){_.S("Failed to start : %s.",a||"")})};xq.prototype.j=function(a){var b=this;return new _.md(function(c,d){b.g.sendMessage(a);_.A(a,1)||d("Unauthenticated");c(a)})};_.wa("default_host._DumpException",function(a){return window.console.error(a.stack)});_.Dg();if(!_.m(yq)||null==yq||yq.I)yq=new xq;

}catch(e){_._DumpException(e)}
}).call(this,this.default_host);
// Google Inc.
